### PR TITLE
argument completions

### PR DESCRIPTION
**Pull request by karitham**
This PR provides completion for all flags and arguments that may be autocompleted.

This PR may break a lot of workflow since those may be working with IDs while we try to work with human readable names.

This PR implements an encrypted cache for autocomplete results, to provide better UX.

### CODE REVIEW

**Comment by karitham** [comment]
I'm not entirely sure the cache is great, but it seems a lot of existing clis do that, and I feel like this is the perfect UX.

There is a bug in the current implementation related to cobra, but it's minimal. (https://github.com/spf13/cobra/issues/1998)

**Comment by karitham** [comment]
The cache implementation is intentionally trivial, but it achieves better UX. Cached completion results are nicer to work with. Although it does depend on the shell an internet speed, I found major difference when trying it out myself.

The cache is also used when trying to handle results from the user.

When interpreting the pod `files/filebrowser`, we first look to the cache to find whether we know what that pod is and what it's ID is. It's minimal but that saves us between 1 and 2 (currently, 2 for apps) roundtrips to the server.

We handle revocation by dealing with it on a TLL+Per-user basis. We only ever have a valid cache when the right user tries to decrypt it, thanks to the encryption.

The cache is considered valid for a minute only, but stays on disk as long as it's not cleaned up.

The minute of validity would be an issue if it was for all command operations, but here we only use it for completion.

We may also implement additional revocation mechanism, such as edition/creation of a resource evicting the cache of said resource.

**Comment by aep** [comment]
doesnt work for me anymore with zsh. 

```
aep@stark: /work/kraud/macro kra pods logs 
‘No matches for: `completions', `filename', or `corrections'’

```

**Comment by karitham** [comment]
That's odd, I tested it with both fish and zsh and the completion worked fine.

It does not work when not logged on (as expected), but no such errors found on my end.

Tested with
```
% zsh --version
zsh 5.9 (x86_64-pc-linux-gnu)
```

And a build of the latest commit here 
```
% make
go build -ldflags="-X 'github.com/kraudcloud/cli/api.Version=v1.3.1-17-g98a90df'" -o kra .
```

Are you using anything special for completions?

I'm no zsh user, so I set up completions like so. Unsure if that makes a difference
```bash
# ~/.zshrc

autoload -U compinit; compinit
eval "$(kra completion zsh)" # `kra` here points to the built binary
```

**Comment by aep** [comment]
my bad. forgot to regen the completions.
i wonder how kubectl does it, since i never had to do that there

**Review by aep — APPROVED** [review]

**Comment by karitham** [comment]
> my bad. forgot to regen the completions.
> i wonder how kubectl does it, since i never had to do that there

The way your shell completions are set up might be different, I never have to re-gen the completions

**Pull request merged**
