### PR TITLE
fix log where tty is false

### PR DESCRIPTION
**Pull request by karitham**
Instead of fighting with docker, since they do it right and we want to keep compability, we embrace it and use their client and packages to handle logs.

This fix refactors the http client slightly to handle auth and docker in a simpler manner.

It also fixes the way version is reported improperly as `1.0.1` in http and `1.1.2` in main.

### CODE REVIEW

**Comment by aep** [comment]
that sounds like a terrible idea, since this means kra now depends on the tls certs to be present with `kra docker setup`. this is super confusing to the user can can lead to subtle bugs

**Comment by karitham** [comment]
`kra` doesn't depend on the cert, we use the docker client for their types and paths, but we overtake it for dialing and authentication

**Comment by aep** [comment]
ah! i got confused by the tcp:// host line. this is a good idea then

**Comment by karitham** [comment]
A yeah, for some reason it needs a scheme to parse the host properly.

The way we do routing at ingress means we need to properly set `Host` header, but for some reason docker insists on having it be `docker` instead of whatever the http client sets, so I have to do that.

**Pull request merged**
