### PR TITLE
`kra logs <pod_aid>`

### PR DESCRIPTION
**Pull request by karitham**
Implement `kra logs` (and `kra pod logs`), similar to `docker logs`.

Unlike docker logs though, we support context properly and autocomplete the available containers and not just local ones.

### CODE REVIEW

**Comment by aep** [comment]
this works better already than docker for me.
the zsh completion is <3

can we have -f somehow instead of --follow?
i'm ok with changing -f file to something else, since wanting log follow is a much more likely case than wanting a different compose file

**Comment by aep** [comment]
also need to think of the UX of namespace.  the syntax is not discoverable:



```
aep@stark: /work/kraud/cli kra ps                                     
aid           namespace         name                cpu     mem     image                                    
p2f1d6cb2128  filedrop_default  filedrop-web-1      2 GHz   2.0 GB  filedrop:if39acccb787

aep@stark: /work/kraud/cli kra logs filedrop-web-1 
Error: unexpected status code: 404

aep@stark: /work/kraud/cli kra logs filedrop_default  filedrop-web-1
Error: accepts 1 arg(s), received 2

aep@stark: /work/kraud/cli kra logs filedrop_default/filedrop-web-1 
works


```


i forgot how kubectl does it

**Review by aep — APPROVED** [review]

**Comment by aep** [comment]
`kra pod logs` should work
we want explicit and short options to be consistent

**Comment by karitham** [comment]
> `kra pod logs` should work

Moving log under pod seems good. kctl and docker both have it as a top level command, but I don't think it matters much, logs do make sense as a subcategory of a pod.

> Also need to think of the UX of namespace. the syntax is not discoverable

Autocomplete works well. `kra pod edit` and `kra pod inspect` both take an `aid` as arguments. I think we should also use that format for `log`, and later on maybe allow other syntax. Simple and consistent for now.

> Can we have -f somehow instead of --follow

Will move the `--file` under related categories that use it (only `image` right now) and have follow take a `-f`.

**Comment by karitham** [comment]
> I forgot how kubectl does it

kubecl has us specify the namespace any-time we want to operate on anything other than the default namespace.

It often looks like `k logs -n media-proxy gateway`. or `k logs gateway -n media-proxy` 

I don't really think this option is nice to use, but it makes it clear that it operates on both namespace and pod.

Space separated namespace and pod is confusing, especially since we often use the same name for namespace and pod. Especially so due to `kubectl` users favoring either form of the above command.

Using AIDs thorough the application does not seem too bad. It's good for scripts.

The `namespace/pod` syntax is quite nice, but it does tend to get lengthy. We also need to stay consistent on this. It should not be the job of the endpoint to map the `namespace/pod` to `aid`.
That's what docker compose does, but we already figured out that's pain.

I propose we accept both `aid` and `namespace/pod`, and have the cli convert both to AIDs. Will open another issue to track this. https://github.com/kraudcloud/cli/issues/7#issue-1807376428

**Comment by aep** [comment]
> Moving log under pod seems good. 

i think we want both, like ps

> Autocomplete works well. kra pod edit and kra pod inspect both take an aid as arguments.

i think thats even worse now. 

```
[130] aep@stark: /work/kraud/cli kra pods logs p
completions:
p0f1ea1aa712  p2f1d6cb2128  p5080dddb42b  p5e75d6aa548  p75cfa5b7236                          
p1782706a918  p31c07dc029e  p55511216d97  p696cd7829ca  pbcf2d060e92    
```

completion should be based on human readable name

**Comment by karitham** [comment]
> completion should be based on human readable name

I will fix completion in another PR altogether.

Will also add completion to `volumes` and `idp` (and all the other objects that can)

**Pull request merged**
